### ISSUE TITLE
Server crash on editor close

### ISSUE THREAD

**Issue by nobotious** [gigabit101/StevesFactoryManager#102]
Forge 31.2.9, mod version 1.15.2-4.0.0-alpha+build.2

when a client closes the Manager GUI, the server takes a dump. I am running a few other mods, so I apologize if this isn't reproducible.

```
[12Jun2020 02:49:52.296] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
--
java.lang.NoSuchMethodError: net.minecraft.network.PacketBuffer.func_218666_n()Ljava/lang/String;
at vswe.stevesfactory.network.PacketSyncProcedureGroups.decode(PacketSyncProcedureGroups.java:37) ~[?:1.15.2-4.0.0-alpha+build.2]
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:120) ~[?:?]
at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_252]
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:120) ~[?:?]
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?]
at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:?]
at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_252]
at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:?]
at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) ~[?:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`
```

**Comment by hnOsmium0001** [comment]
This should be fixed in alpha+build.3
